class User {
  late final int id;
  late final String name;
  late final String email;
  late final String createdAt;
  late final String updatedAt;
  String? token;

  // User(
  //     {required this.id,
  //     required this.name,
  //     required this.email,
  //     required this.createdAt,
  //     required this.updatedAt});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    email = json['email'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    token = json['token'];
  }
}

// class Autogenerated {
//   User? user;
//   String? token;
//   bool? status;

//   Autogenerated({this.user, this.token, this.status});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     user = json['user'] != null ? new User.fromJson(json['user']) : null;
//     token = json['token'];
//     status = json['status'];
//   }
// }
